services:
  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: src/ProductService/Dockerfile

